"""Updated img_src

Revision ID: 4ee925f1c314
Revises: e1bbf7a86e1f
Create Date: 2024-05-14 13:15:55.863393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ee925f1c314'
down_revision: Union[str, None] = 'e1bbf7a86e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('img_src', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'image_src')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_src', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'img_src')
    # ### end Alembic commands ###
