"""Unique survey id

Revision ID: 4e52493378af
Revises: 668d575e1537
Create Date: 2024-05-23 13:43:52.456243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4e52493378af'
down_revision: Union[str, None] = '668d575e1537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_survey_id', table_name='survey')
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.create_index('ix_survey_id', 'survey', ['id'], unique=False)
    # ### end Alembic commands ###
